POST http://localhost:3003/api/users
Content-Type: application/json
//const saltRounds = 10
//const passwordHash = await bcrypt.hash(password, saltRounds)

{
  "username": "Akuankka",
  "name": "Aku Ankka",
  "password": "Top Secret"
}